### ISSUE TITLE
Repository url

### ISSUE THREAD

**Issue by hedinne** [ueno-llc/ueno-atom-menu#4]
Hey Guys,
[Daiki Ueno](https://github.com/ueno) is probably a nice guy and everything but he is taking all the credit for this package. You should change package.json from
` { "repository": "https://github.com/ueno/ueno-atom-menu" }`
to this
`{ "repository": "https://github.com/ueno-llc/ueno-atom-menu" }` 

All the best, Hedinn

**Comment by baldurh** [comment]
Bwahaha! Thanks Hedinn! 🤣
You just missed a great chance for a PR 😉

**Comment by hedinne** [comment]
Yeah I thought about making a PR but if felt a bit too small to be "contributing to open source" ;)
